# Generated by Django 5.1.4 on 2024-12-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notendur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tegund_okutaekis', models.CharField(max_length=100)),
                ('framleidandi', models.CharField(max_length=100)),
                ('gerd', models.CharField(max_length=100)),
                ('nafn', models.CharField(max_length=100)),
                ('simanumer', models.CharField(max_length=15)),
                ('kennitala', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('lysing', models.TextField()),
                ('buid_til', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
